name:                Luigi
version:             0.1.0.0
github:              "viluon/Luigi"
license:             BSD3
author:              "Andrew Kvapil"
maintainer:          "viluon@espiv.net"
copyright:           "2019 Andrew Kvapil"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/viluon/Luigi#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5.3 && < 0.6

library:
  source-dirs: src

executables:
  Luigi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Luigi

tests:
  Luigi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Luigi
